source "https://rubygems.org"

# Default Gems
if facterversion = ENV['FACTER_GEM_VERSION']
  gem 'facter', facterversion
else
  gem 'facter'
end
if puppetversion = ENV['PUPPET_GEM_VERSION']
  gem 'puppet', puppetversion
else
  gem 'puppet'
end
gem 'rake'
gem 'puppet-lint'
gem 'puppet-syntax'

group :test do
  gem 'rspec-puppet'
  gem 'puppetlabs_spec_helper'
  gem 'beaker-rspec'
end
